# Generated by Django 5.2.3 on 2025-06-11 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_price_currency',
            field=models.CharField(choices=[('UZS', "So'm"), ('USD', 'Dollar'), ('RUB', 'Rubl')], default='UZS', max_length=3),
        ),
    ]
