# Generated by Django 5.2.3 on 2025-06-11 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_store', '0002_product_product_price_currency'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_descriptions',
            new_name='product_descriptions_ru',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_name',
            new_name='product_name_ru',
        ),
        migrations.AddField(
            model_name='product',
            name='product_descriptions_uz',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='product_name_uz',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
