# Generated by Django 5.2.3 on 2025-06-12 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_store', '0009_botuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='botuser',
            old_name='user_fullname',
            new_name='full_name',
        ),
        migrations.RenameField(
            model_name='botuser',
            old_name='user_phone_number',
            new_name='phone_number',
        ),
    ]
